replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: ruby
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 1
    memory: 4Gi
ingress:
  enabled: true
basedomain: localhost
