replicaCount: 1
image:
  pullPolicy: IfNotPresent
service:
  name: ruby
  type: ClusterIP
  externalPort: 80
  internalPort: 3000
webpackDevServer:
  externalPort: 81
  internalPort: 3001
ingress:
  enabled: true
basedomain: localhost
