version: 2
jobs:
  build_and_push:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build . -t mtsmfm/gh-deck:$CIRCLE_SHA1 --cache-from mtsmfm/gh-deck:latest
      - run: docker tag mtsmfm/gh-deck:$CIRCLE_SHA1 mtsmfm/gh-deck:latest
      - run: docker push mtsmfm/gh-deck:$CIRCLE_SHA1
      - run: docker push mtsmfm/gh-deck:latest
workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push
