{{ if .Values.certificate.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ template "fullname" . }}
spec:
  secretName: {{ template "fullname" . }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: {{ .Values.host }}
  dnsNames:
  - {{ .Values.host }}
  acme:
    config:
    - http01:
        ingress: {{ template "fullname" . }}
      domains:
        - {{ .Values.host }}
{{ end }}
