apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ['bin/rails', 'r', 'User.find_each {|u| ImportGithubReceivedEventsJob.perform_now(u) }']
            {{ if .Values.mountLocal }}
            volumeMounts:
            - name: approot
              mountPath: /app
            {{ end }}
            env:
            - name: DATABASE_URL
              value: {{ .Values.databaseUrl }}
          restartPolicy: Never
          {{ if .Values.mountLocal }}
          volumes:
          - name: approot
            hostPath:
              path: {{ .Values.currentDir }}
          {{ end }}
