apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ['bin/rails', 'r', '"User.find_each {|u| ImportGithubReceivedEventsJob.perform_now(u) }"']
            volumeMounts:
            - name: approot
              mountPath: /app
            env:
            - name: DATABASE_URL
              value: postgresql://postgres:mysecretpassword@{{ template "fullname" . }}-postgres
          restartPolicy: Never
          volumes:
          - name: approot
            hostPath:
              path: {{ .Values.currentDir }}
