apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "fullname" . }}
spec:
  schedule: "*/1 * * * *"
  startingDeadlineSeconds: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ['bin/rails', 'r', 'User.find_each {|u| ImportGithubReceivedEventsJob.perform_now(u) }']
            {{ if .Values.mountLocal }}
            volumeMounts:
            - name: approot
              mountPath: /app
            {{ end }}
            env:
            {{ if .Values.databaseUrl }}
            - name: DATABASE_URL
              value: {{ .Values.databaseUrl }}
            {{ end }}
            {{ if .Values.databaseHost }}
            - name: DATABASE_HOST
              value: {{ .Values.databaseHost }}
            {{ end }}
            {{ if .Values.databaseUser }}
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databaseUser.secretKeyRef.name }}
                  key: {{ .Values.databaseUser.secretKeyRef.key }}
            {{ end }}
            {{ if .Values.databasePassword }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.databasePassword.secretKeyRef.name }}
                  key: {{ .Values.databasePassword.secretKeyRef.key }}
            {{ end }}
            {{ if .Values.railsEnv }}
            - name: RAILS_ENV
              value: {{ .Values.railsEnv }}
            {{ end }}
          restartPolicy: Never
          {{ if .Values.mountLocal }}
          volumes:
          - name: approot
            hostPath:
              path: {{ .Values.currentDir }}
          {{ end }}
