apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}
    spec:
      containers:
      - &main
        name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        stdin: true
        tty: true
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: approot
          mountPath: /app
        env:
        - name: GITHUB_CLIENT_ID
          value: {{ .Values.githubClientId }}
        - name: GITHUB_CLIENT_SECRET
          value: {{ .Values.githubClientSecret }}
        - name: DATABASE_URL
          value: postgresql://postgres:mysecretpassword@{{ template "fullname" . }}-postgres
      - <<: *main
        name: {{ .Chart.Name }}-console
        command: ['sh', '-c', 'while true; do sleep 1; done']
        ports: []
      - <<: *main
        name: {{ .Chart.Name }}-webpack-dev-server
        command: ['bin/webpack-dev-server']
        ports:
        - containerPort: {{ .Values.webpackDevServer.internalPort }}
      - <<: *main
        name: {{ .Chart.Name }}-relay-compiler
        command: ['yarn', 'run', 'relay', '--', '--watch']
        ports: []
      volumes:
      - name: approot
        hostPath:
          path: {{ .Values.currentDir }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-postgres
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        buildID: {{ .Values.buildID }}
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app: {{ template "fullname" . }}-postgres
    spec:
      containers:
      - name: {{ .Chart.Name }}-postgres
        image: postgres:10.3-alpine
        volumeMounts:
        - name: pg-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pv0001
