apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  - port: {{ .Values.webpackDevServer.externalPort }}
    targetPort: {{ .Values.webpackDevServer.internalPort }}
    protocol: TCP
    name: webpack-dev-server
  selector:
    app: {{ template "fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-postgres
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}-postgres
