default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development
  <% url = URI.parse(ENV.fetch("DATABASE_URL")) %>
  host: <%= url.host %>
  user: <%= url.user %>
  password: <%= url.password %>

test:
  <<: *default
  database: app_test
  host: <%= url.host %>
  user: <%= url.user %>
  password: <%= url.password %>

production:
  <<: *default
  database: app_production
