default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% url = URI.parse(ENV.fetch("DATABASE_URL", "")) %>
  host: <%= url.host || ENV.fetch("DATABASE_HOST") %>
  user: <%= url.user || ENV.fetch("DATABASE_USER") %>
  password: <%= url.password || ENV.fetch("DATABASE_PASSWORD") %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
