apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gh-deck
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import-gh-events
            env:
            - name: DATABASE_HOST
              value: gh-deck-postgres
            - name: DATABASE_USER
              value: postgres
            - name: DATABASE_PASSWORD
              value: mysecretpassword
