apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gh-deck
spec:
  secretName: gh-deck-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: gh-deck.net
  dnsNames:
  - gh-deck.net
  acme:
    config:
    - http01:
        ingress: gh-deck
      domains:
        - gh-deck.net
