apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gh-deck
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import-gh-events
            env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_HOST
              value: gh-deck-rails-cloudsql-proxy
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            resources:
              requests:
                memory: "100Mi"
                cpu: "50m"
              limits:
                memory: "200Mi"
                cpu: "100m"
